FROM ubuntu:16.04
#Installing Base OS 

MAINTAINER cyrilsebastian<cyrilsebastian01@gmail.com>


#Updating the OS
RUN apt-get update
#Installing nodejs and dependency 
Run apt-get install -y nodejs npm

#Creating a directory to place nodejs files
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app


# Install docker app dependencies
COPY package.json /usr/src/app/
COPY index.js /usr/src/app/

#Giving excutable rights to the file
RUN chmod +x /usr/src/app/index.js

#adding the port number for nodejs webserver
EXPOSE 8000

#Starting npm
CMD [ "npm", "start" ]